# Generated by Django 6.0 on 2025-12-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_profile_rename_content_post_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('project', 'Project'), ('event', 'Event')], default='project', max_length=10),
        ),
    ]
