# Generated by Django 6.0 on 2025-12-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_post_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_subtitle',
            field=models.CharField(default='Cybersecurity • Full-stack • Robotics', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_title',
            field=models.CharField(default='Building systems, not just software.', max_length=200),
        ),
    ]
