# Generated by Django 6.0 on 2025-12-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_profile_hero_subtitle_profile_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
