# Generated by Django 5.0.6 on 2026-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0008_sitestat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_featured",
        ),
        migrations.AddField(
            model_name="post",
            name="external_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("project", "Project"), ("event", "Event")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
