# Generated by Django 5.0.6 on 2026-03-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0009_remove_post_is_featured_post_external_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("project", "Project"), ("event", "Event")],
                default="project",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="posts/videos/"),
        ),
    ]
