# Generated by Django 4.2.13 on 2026-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_post_is_featured_alter_post_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='Turn on to display the maintenance page and block access to the site.')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
